# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:               Covid in Wisconsin
tagline:             ''
description:         'A blog for unique analysis of Covid data in Wisconsin.'
url:                 https://test.covid-wisconsin.com
baseurl:             /

# About/contact
author:
  name:              Matt Bayer
  url:               https://twitter.com/MattBayer3
  email:             

paginate:         5

# Custom vars
version:          2.1.0
